### ISSUE TITLE
Select Form for Options

### ISSUE THREAD

**Issue by spolica** [spolica/JS-Ember-Ledger#1]
http://stackoverflow.com/questions/35540919/create-a-form-select-list-in-ember-2-2

**Comment by polina13** [comment]
2internal-model.js:502Uncaught Error: Attempted to handle event `deleteRecord` on <js-ember-ledger@model:entry::ember647:-KFBmtsxBYBGybaYYouT> while in state root.deleted.saved. 
deleteEntry()
